name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux_tests:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: true
      matrix:
        php: [8.0, 8.1, 8.2, 8.3]
        phpunit: ['10', '11']
        stability: [prefer-lowest, prefer-stable]

    name: PHP ${{ matrix.php }} - PHPUnit ${{ matrix.phpunit }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, igbinary, msgpack, lzf, zstd, lz4, memcached, gmp, :php-psr
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Set PHPUnit
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require phpunit/phpunit:^${{ matrix.phpunit }} --dev --no-interaction --no-update

      - name: Install dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit --display-deprecation

  windows_tests:
    runs-on: windows-2022

    strategy:
      fail-fast: true
      matrix:
        php: [8.3]
        phpunit: ['10', '11']
        stability: [prefer-lowest, prefer-stable]

    name: PHP ${{ matrix.php }} - PHPUnit ${{ matrix.phpunit }} - ${{ matrix.stability }} - Windows

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, gd, pdo_mysql, fileinfo, ftp, redis, memcached, gmp, intl, :php-psr
          tools: composer:v2
          coverage: none

      - name: Set PHPUnit
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require phpunit/phpunit:^${{ matrix.phpunit }} --dev --no-interaction --no-update
          shell: bash

      - name: Install dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit